services:

  dashboard:
    depends_on:
      populate_db:
        condition: service_completed_successfully
    build:
      context: ./
      dockerfile: ./devops/app/webapp-Dockerfile
    container_name: dashboard
    restart: always
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PORT=5432
      - PG_DBNAME=postgres
      - PG_PASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
    ports:
      - "${DASHBOARD_PORT:-8050}:80"
    networks:
      - network

  db:
    image: timescale/timescaledb-ha:pg16
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 24
    volumes:
      - ./devops/db/schema_synthetic.sql:/docker-entrypoint-initdb.d/schema_synthetic.sql
    networks:
      - network

  populate_db:
    container_name: populate_db
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./devops/populate_db/pg_populate-Dockerfile
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
      - PGPASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
    volumes:
      - ./devops/populate_db/SyntheticData:/wd
    networks:
      - network

networks:
  network:
    driver: bridge
